version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t lcasper/34-qmk-ferris-sweep .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar lcasper/34-qmk-ferris-sweep
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Creating keymap Artifact
          command: |
            cp /qmk_firmware/ferris_sweep_lassieee.hex /tmp/ferris_sweep_lassieee.hex
      - store_artifacts:
          path: /tmp/ferris_sweep_lassieee.hex
          destination: ferris_sweep_lassieee.hex
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
