version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.12-git
      #- image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run QMK container and compile keymap
          command: |
            export
            cd /app;
            docker run -d --rm --name qmk qmkfm/qmk_firmware sleep 120;
            docker exec -it qmk qmk setup
            docker exec -it qmk qmk env
            docker exec -it qmk mkdir /qmk_firmware/keyboards/ferris/keymaps/lassieee
            for i in config.h keymap.c rules.mk; do
                docker cp $i qmk:qmk_firmware/keyboards/ferris/keymaps/lassieee/
            done
            docker exec -it qmk qmk compile -kb ferris/sweep -km lassieee
            docker cp qmk:/qmk_firmware/ferris_sweep_lassieee.hex .
            docker stop qmk
      - store_artifacts:
          path: /app/ferris_sweep_lassieee.hex
      - persist_to_workspace:
          root: /app
          paths:
            - ferris_sweep_lassieee.hex

  publish_github_release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - checkout
      - attach_workspace:
          at: /app
      - run:
          name: "Publish release on GitHub"
          command: |
            git tag
            VERSION=$(git tag | sort -V | tail -1)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(git tag | sort -V | tail -1)  /app/ferris_sweep_lassieee.hex

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish_github_release:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci
            tags:
              only: /^\d+\.\d+\.\d+$/
#              only: /^[0-9]\.[0-9]\.[0-9]$/

